# Generated by Django 3.2.7 on 2021-10-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_name', models.CharField(max_length=56, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=516)),
                ('rating', models.FloatField(null=True)),
                ('ingredient', models.ManyToManyField(to='fridge_cleaner_app.Ingredient')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge_cleaner_app.sourcesite')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge_cleaner_app.ingredienttyp'),
        ),
    ]
