# Generated by Django 3.2.7 on 2021-11-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_cleaner_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
