# Generated by Django 3.2.7 on 2021-11-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_cleaner_app', '0002_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='SourceSite',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='fridge_cleaner_app.Tags'),
        ),
    ]
