# Generated by Django 3.2.7 on 2021-11-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_cleaner_app', '0003_auto_20211112_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
